export enum ACTION_TYPE {
  GRANTING_MERITBADGE_AND_RANKS="GRANTING_MERITBADGE_AND_RANKS",
  CREATE_ORGANIZATION="CREATE_ORGANIZATION",
  GRANTING_FUNCTION="GRANTING_FUNCTION",
  REVOKING_FUNCTION="REVOKING_FUNCTION",
}
